config/routes.rb
Rails.application.routes.draw do
  resources :vehicles

  # Set root
  root 'vehicles#index'

  resources :vehicles do
    collection { post :import }
  end

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  def self.decision_tree
    @decision_tree ||= calculate_decision_tree
  end

  def prediction
    @prediction ||= calculate_prediction
  end

  def good_prediction?
    prediction == status
  end

  # CSV Importer class method
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Vehicle.create! row.to_hash
    end
  end

  # CSV Downloader class method
  def self.to_csv(vehicles)
    CSV.generate do |csv|
      csv << column_names
      vehicles.each do |vehicle|
        csv << vehicle.attributes.values_at(*column_names)
      end
    end
  end

  private

  def calculate_prediction
    data =  [self[:year], self[:make], self[:mileage], self[:fuel], self[:repairs], self[:services], self[:status]]
    self.class.decision_tree.predict(data)
  end

  def self.calculate_decision_tree
    historical_data_set = Vehicle.where(historical: true)

    # Convert the query results to
    converted_historical = historical_data_set.map { |h| [h[:year], h[:make], h[:mileage], h[:fuel], h[:repairs], h[:services], h[:status]]}

    # Instantiate the tree, and train it based on the data (set default to '1')
    attributes = ['year', 'make', 'mileage', 'fuel', 'repairs', 'services']
    dec_tree = DecisionTree::ID3Tree.new(attributes, converted_historical, 'Retired', year: :discrete, make: :discrete, mileage: :continuous, fuel: :discrete, repairs: :continuous, services: :continuous)
    dec_tree.train
    dec_tree
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    # Make the queries from the database
    @displayed_vehicles = Vehicle.all


    # attributes = ['Temperature']
    # training = [
    #     [36.6, 'healthy'],
    #     [37, 'sick'],
    #     [38, 'sick'],
    #     [36.7, 'healthy'],
    #     [40, 'sick'],
    #     [50, 'really sick'],
    # ]
    #
    # dec_tree = DecisionTree::ID3Tree.new(attributes, training, 'sick', :continuous)
    # dec_tree.train
    #
    # test = [37, 'sick']
    # decision = dec_tree.predict(test)
    # p training
    # puts "Predicted: #{decision} ... True decision: #{test.last}"



    respond_to do |format|
      format.html
      format.csv { render text: Vehicle.to_csv(@displayed_vehicles.reject(&:good_prediction?)) }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Importer
  def import
    Vehicle.import(params[:file])
    redirect_to vehicles_path, notice: "Companies Added Successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:unit, :year, :make, :model, :plate, :mileage, :vin, :category, :color, :status, :equipment, :fuel, :weight, :transmission, :custom, :purchase_code, :purchase_price, :start_cost, :virtual_meter, :repairs, :services)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Truckwatcher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          CS5331 Project 2 | <em>Demo Web App</em>
        </h1>

        <hr>
        <p style="text-align: center;">
          <a id="modal-923712" href="#modal-container-923712" role="button" class="btn btn-primary btn-large" data-toggle="modal">BACKGROUND & OBJECTIVES</a>
        </p>
      </div>


      <div class="modal fade" id="modal-container-923712" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h4 class="modal-title" id="myModalLabel">
                BACKGROUND AND OBJECTIVES
              </h4>
            </div>
            <div class="modal-body">
              <p>The second project of the semester entails an investigation of rule mining techniques and their implementation using the WEKA tool.  For this project, students were instructed to investigate their choice of two different rule types:  association rules (as derived by the Apriori family of algorithms) and decision tree rules (using decision trees like C4.5).</p>
              <p>The goals of this project lined up perfectly with what I sought to achieve in this course:  to learn effective new data mining techniques to increase the efficiency of the company I work for.  Therefore, I chose to stick within the domain of what our company deals with on a typical day-to-day basis.  Our development team had just completed a Fleet Asset System which tracks all vehicle assets owned by the company, along with their service and maintenance history.  One common problem that our administrators face is when to determine a vehicle has outlived its usefulness, or has become too expensive to maintain and continue using.  This is a particularly troublesome problem in our company, as we have upwards of 600 fleet vehicles at any time and the administrators may not be able to inspect each one personally.  Therefore, I hypothesize that by using past historical data regarding fleet assets and the conditions under which they were retired, a decision tree algorithm can be used on current fleet assets to flag vehicles that should be inspected personally and be placed under consideration for retirement.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>

      </div>


        <%= yield %>


    </div>
  </div>
</div>

</body>
</html>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :plate %><br>
    <%= f.text_field :plate %>
  </div>
  <div class="field">
    <%= f.label :mileage %><br>
    <%= f.number_field :mileage %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :equipment %><br>
    <%= f.text_field :equipment %>
  </div>
  <div class="field">
    <%= f.label :fuel %><br>
    <%= f.text_field :fuel %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :transmission %><br>
    <%= f.text_field :transmission %>
  </div>
  <div class="field">
    <%= f.label :custom %><br>
    <%= f.text_field :custom %>
  </div>
  <div class="field">
    <%= f.label :purchase_code %><br>
    <%= f.number_field :purchase_code %>
  </div>
  <div class="field">
    <%= f.label :purchase_price %><br>
    <%= f.text_field :purchase_price %>
  </div>
  <div class="field">
    <%= f.label :start_cost %><br>
    <%= f.text_field :start_cost %>
  </div>
  <div class="field">
    <%= f.label :virtual_meter %><br>
    <%= f.number_field :virtual_meter %>
  </div>
  <div class="field">
    <%= f.label :repairs %><br>
    <%= f.number_field :repairs %>
  </div>
  <div class="field">
    <%= f.label :services %><br>
    <%= f.number_field :services %>
  </div><br>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>

<hr>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<span class="pull-left">
  <%= link_to 'Add a New Vehicle', new_vehicle_path %>
</span>
<span class="pull-right">
  <%= link_to 'Download CSV', vehicles_path(format: :csv) %>
</span>

<br>
<br>
<table class="table table-hover table-striped table-condensed">
  <thead>
  <tr>
    <th>
      Unit ID
    </th>
    <th>
      Year
    </th>
    <th>
      Make
    </th>
    <th>
      Model
    </th>
    <th>
      Plate
    </th>
    <th>
      Status
    </th>
    <th>
      Prediction
    </th>
    <th>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @displayed_vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.unit %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.plate %></td>
        <td><%= vehicle.status %></td>
        <td>
          <span class="label <%= vehicle.good_prediction? ? 'label-success' : 'label-danger' %>">
            <%= vehicle.good_prediction? ? 'Accurate' : 'Needs Attention' %>
          </span>
        </td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>




<hr>

<div class="well">
  <h3>Import Vehicles</h3>
  <em>Only upload with correct column headings</em>
  <br>
  <br>
  <%= form_tag import_vehicles_path, multipart: true do %>
      <%= file_field_tag :file %><br>
      <%= submit_tag "Upload Vehicles", class: 'btn btn-default' %>
  <% end %>
</div>


<hr>

app/views/vehicles/new.html.erb
<%= link_to 'Home', vehicles_path %> / <em>New Vehicle Form</em>
<h1>New vehicle</h1>

<%= render 'form' %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unit:</strong>
  <%= @vehicle.unit %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Plate:</strong>
  <%= @vehicle.plate %>
</p>

<p>
  <strong>Mileage:</strong>
  <%= @vehicle.mileage %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @vehicle.vin %>
</p>

<p>
  <strong>Category:</strong>
  <%= @vehicle.category %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicle.color %>
</p>

<p>
  <strong>Status:</strong>
  <%= @vehicle.status %>
</p>

<p>
  <strong>Equipment:</strong>
  <%= @vehicle.equipment %>
</p>

<p>
  <strong>Fuel:</strong>
  <%= @vehicle.fuel %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @vehicle.weight %>
</p>

<p>
  <strong>Transmission:</strong>
  <%= @vehicle.transmission %>
</p>

<p>
  <strong>Custom:</strong>
  <%= @vehicle.custom %>
</p>

<p>
  <strong>Purchase code:</strong>
  <%= @vehicle.purchase_code %>
</p>

<p>
  <strong>Purchase price:</strong>
  <%= @vehicle.purchase_price %>
</p>

<p>
  <strong>Start cost:</strong>
  <%= @vehicle.start_cost %>
</p>

<p>
  <strong>Virtual meter:</strong>
  <%= @vehicle.virtual_meter %>
</p>

<p>
  <strong>Repairs:</strong>
  <%= @vehicle.repairs %>
</p>

<p>
  <strong>Services:</strong>
  <%= @vehicle.services %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>